### ISSUE TITLE
LondonUnderground.py crash with 'STAND BACK TRAIN APPROACHING' warning turned on.

### ISSUE THREAD

**Issue by jfoot** [jfoot/Bus-Departure-Board#3]
**Describe the bug**
With the 'STAND BACK TRAIN APPROACHING' warning message turned the program will crash eventually. 

**To Reproduce**
1. Turn on the 'STAND BACK TRAIN APPROACHING' warning message.
2. Leave running for several hours and then it might eventually crash.

**Expected behaviour**
It should be able to run non-stop without issue.

**Screenshots**
```
Traceback (most recent call last):
  File "/home/pi/Bus-Departure-Board/LondonUnderground.py", line 722, in <module>
    display()
  File "/home/pi/Bus-Departure-Board/LondonUnderground.py", line 670, in display
    board.tick()
  File "/home/pi/Bus-Departure-Board/LondonUnderground.py", line 591, in tick
    self.bottom.tick()
  File "/home/pi/Bus-Departure-Board/LondonUnderground.py", line 447, in tick
    self.image_composition.remove_image(self.IDestination)
  File "/usr/local/lib/python2.7/dist-packages/luma/core/image_composition.py", line 161, in remove_image
    self.composed_images.remove(image)
ValueError: list.remove(x): x not in list
```

**Program information:**
 - Pi Type - Pi Zero WH
 - Program - LondonUnderground.py
 - Version - 1.1.LU

**Comment by jfoot** [comment]
This has now been fixed in version 2.1.LU, I forgot to check for his the bottom row wasn't actually currently displaying a service before trying to clear it from the display.
