### ISSUE TITLE
Unable to install on Raspberry Pi Zero WH

### ISSUE THREAD

**Issue by barronoid2** [jfoot/Bus-Departure-Board#39]
**Describe the bug**
I have tried a few times to install Departure Board on a Raspberry Pi Zero WH. I've tried it with both the Lite and Legacy Lite 32 bit OS.

There is an error this early step:

display@raspberrypia:~ $ sudo apt install python3-dev python3-pip python3-numpy python3-lxml libfreetype6-dev libjpeg-dev build-essential python3-pil  zlib1g-dev liblcms2-dev libopenjp2-7 libtiff6 -y
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package libtiff6

Then it fails on the final step:

(Bus-Departure-Board) display@raspberrypia:~/Bus-Departure-Board $ python3 DemoPy3.py
Traceback (most recent call last):
  File "/home/display/Bus-Departure-Board/DemoPy3.py", line 12, in <module>
    from PIL import ImageFont, Image, ImageDraw
  File "/home/display/Bus-Departure-Board/lib/python3.9/site-packages/PIL/ImageFont.py", line 39, in <module>
    from . import Image
  File "/home/display/Bus-Departure-Board/lib/python3.9/site-packages/PIL/Image.py", line 100, in <module>
    from . import _imaging as core
ImportError: libopenjp2.so.7: cannot open shared object file: No such file or directory

Can you help? Thanks
Andrew

**Comment by jfoot** [comment]
Hey @barronoid2, I'll try and take a look into this on the weekend, I'll dig out my old Pi Zero.

**Comment by barronoid2** [comment]
Thanks. I appreciate it.

**Comment by gui1207** [comment]
Hi @barronoid2,

 I'm also using Raspberry Pi Zero WH and managed to install and run.

Here is my OS:
```
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
