### ISSUE TITLE
NationalRail.py fatal crash due to type error, expected integer but got float.

### ISSUE THREAD

**Issue by jfoot** [jfoot/Bus-Departure-Board#5]
**Describe the bug**
The program will completely crash and the display screen shows blank. The error logs are attached below.

**To Reproduce**
Steps to reproduce the behaviour:
- Leave the program running for several days and eventually it might crash.

**Expected behaviour**
The program should be able to run indefinitely. 

**Screenshots or Error Trace**
```
TypeError: integer argument expected, got float
<urlopen error [Errno -3] Temporary failure in name resolution>
Traceback (most recent call last):
  File "/home/pi/Bus-Departure-Board/NationalRailPy3.py", line 787, in <module>
    display()
  File "/home/pi/Bus-Departure-Board/NationalRailPy3.py", line 737, in display
    image_composition.refresh()
  File "/usr/local/lib/python3.7/dist-packages/luma/core/image_composition.py", line 179, in refresh
    img.position)
  File "/usr/local/lib/python3.7/dist-packages/PIL/Image.py", line 1506, in paste
    self.im.paste(im, box)
TypeError: integer argument expected, got float

```
**Program information:**
 - Pi Type - Pi Zero WH
 - Program - NationalRailPy3.py
 - Version 2.0.NR

**Comment by jfoot** [comment]
This looks like an issue with the PIL Library as opposed to an issue with my own code. I have implemented more ways to log the output using " >> NationalRail.log 2>&1" and shall try to reproduce this error to confirm my suspicions.

**Comment by jfoot** [comment]
The same bug can occur on the the LondonUndergroundPy3.py (V2.1.LU) program:

The failure seems to always occur after a failed data-request for some strange reason.... 

```
GetData() ERROR
<urlopen error [Errno -3] Temporary failure in name resolution>
New Data Retrieved 11:25:54.351431
Traceback (most recent call last):
  File "/home/pi/Bus-Departure-Board/LondonUndergroundPy3.py", line 736, in <module>
    display()
  File "/home/pi/Bus-Departure-Board/LondonUndergroundPy3.py", line 687, in display
    image_composition.refresh()
  File "/usr/local/lib/python3.7/dist-packages/luma/core/image_composition.py", line 179, in refresh
    img.position)
  File "/usr/local/lib/python3.7/dist-packages/PIL/Image.py", line 1506, in paste
    self.im.paste(im, box)
TypeError: integer argument expected, got float
```

**Comment by jfoot** [comment]
This also now seems to be effecting NationalBusesPy3.py (V2.1.NB)... It looks like it's related to the refresh image function and currently I believe it to be an error in the Luma.OLED/Core or PIL library. Still not sure and trying to debug further...

```
GetData() ERROR
'all'
Traceback (most recent call last):
  File "/home/pi/Bus-Departure-Board/NationalBusesPy3.py", line 784, in <module>
    display()
  File "/home/pi/Bus-Departure-Board/NationalBusesPy3.py", line 736, in display
    image_composition.refresh()
  File "/usr/local/lib/python3.7/dist-packages/luma/core/image_composition.py", line 179, in refresh
    img.position)
  File "/usr/lib/python3/dist-packages/PIL/Image.py", line 1459, in paste
    self.im.paste(im, box)
TypeError: integer argument expected, got float

```
